version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_GEMINI_API=${VITE_GEMINI_API}
    ports:
      - "3000:80"
    restart: unless-stopped
    
  # Optional: Add a development service
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_GEMINI_API=${VITE_GEMINI_API}
    profiles:
      - dev